### PR TITLE
Support very large strings

### PR DESCRIPTION
**Pull request by non**
This PR adds the ability to parse really big strings. Previously, valid strings larger than 1-2M would fail to parse. After this PR, it will definitely be able to handle at least 1G strings.

I think this is a good change, although in general the presence of very large strings in JSON is often a sign that something went wrong. I thought about making the support optional but that seems like too many levers. I'm also open to closing this PR if overall people prefer the fail fast behavior.

What do you all think? I'd like to do a new Jawn release soon (there are some other small changes too).

/cc @easel @travisbrown

### CODE REVIEW

**Comment by non** [comment]
I did some ad-hoc benchmarking that indicated this change wouldn't hurt performance but I'll try to post a side-by-side benchmark to help indicate this.

**Comment by travisbrown** [comment]
Assuming this isn't going to hurt performance for more common situations, I'm all for it.

**Comment by non** [comment]
So I tested this with a reasonably large file. Small-ish files get read as strings by the `ChannelParser` so they aren't a good test of this change, although I did verify that assumption.

As far as this test file, it's randomly-generated JSON:

> erik@icebreaker ~/w/jawn (topic/grow-buffers) π du -sh benchmark/src/main/resources/yo30.json
>  34M    benchmark/src/main/resources/yo30.json

These are the results from *topic/grow-buffers*:

```
[info] Yo30Bench.jawnParse             avgt   10  237.679 ±  5.459  ms/op
[info] Yo30Bench.jawnStringParse       avgt   10  217.539 ± 13.156  ms/op

And these are from *master*:

```
[info] Yo30Bench.jawnParse             avgt   10  240.682 ± 16.732  ms/op
[info] Yo30Bench.jawnStringParse       avgt   10  240.909 ± 33.744  ms/op

Looks pretty reasonable to me. I gave each run 10 warmups and 10 runs.

**Comment by non** [comment]
For those following along at home, the concern is that I added a branch to some very low-level methods in `ChannelParser` (`byte` and `at`) which we want to be as fast as possible.

The reason I didn't expect them to become slower is that we were already doing a branch check, and the first branch is the one we overwhelmingly expect to be in (assuming the average read is 10 bytes we will only hit the second branch 1-in-100k times or so). Since the additional branch check only happens then it seems like we're just making a very marginal branch a little bit slower.

**Pull request merged**
