### PR TITLE
Bumped to Play Json 2.5

### LINKED ISSUE #52: Add Support for Play Json 2.5
Add support for Play 2.5

I will make a pull request for this, as it should be just a single bump of a version

### PR DESCRIPTION
**Pull request by mdedetrich**
Fixes #52

### CODE REVIEW

**Comment by mdedetrich** [comment]
Hmm, there seems to be an issue, Play 2.5.x isn't available for Scala 2.10.x, let me see if I can adjust the build so its not built for Scala 2.10.x

**Comment by non** [comment]
I'll try to figure out some way to deal with this.

**Comment by mdedetrich** [comment]
I think you have to use sbt-doge to solve this problem (https://github.com/sbt/sbt-doge). I gave up when I tried some time ago

**Comment by non** [comment]
Just released 0.10.0 which supports Play 2.5.8. I'm closing this PR -- feel free to open another one if anything else comes up.

**Pull request closed without merging**
