### PR TITLE
Fixed the benchmark compilation errors 

### PR DESCRIPTION
**Pull request by etorreborre**
and the benchmark command in the README

@non this is fixing #91

### CODE REVIEW

**Comment by tlossen** [comment]
👍

**Comment by etorreborre** [comment]
Thanks I didn't see that. It's fixed now.

**Comment by non** [comment]
Hi @etorreborre, it looks like this got updated independently.

Thanks for your PR and sorry I failed to merge it.

**Comment by etorreborre** [comment]
No worries :-)

**Pull request closed without merging**
